media:
  - name: projects
    label: "Project Attachments"
    input: public/projects/attachments
    output: /projects/attachments
  - name: text
    label: "Text Attachments"
    input: public/text/attachments
    output: /text/attachments
content:
  - name: projects
    label: Projects
    type: collection
    path: public/projects
    view:
      fields: [ date, title, redirect, eleventyExcludeFromCollections ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: eleventyExcludeFromCollections, label: Draft, type: boolean }
      - { name: redirect, label: Redirect, type: string }
      - { name: body, label: Body, type: rich-text }
    filename: "{primary}.md"
  - name: text
    label: Text
    type: collection
    path: public/text
    view:
      fields: [ date, title, redirect, eleventyExcludeFromCollections ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: eleventyExcludeFromCollections, label: Draft, type: boolean }
      - { name: redirect, label: Redirect, type: string }
      - { name: body, label: Body, type: rich-text }
    filename: "{primary}.md"
  - name: history
    label: History
    type: file
    path: public/history/index.md
    fields:
      - { name: layout, type: string, hidden: true }
      - { name: body, label: Body, type: rich-text }