media:
  - name: text
    label: "Text Attachments"
    input: public/text/attachments
    output: /text/attachments
  - name: projects
    label: "Project Attachments"
    input: public/projects/attachments
    output: /projects/attachments
content:
  - name: projects
    label: Projects
    type: collection
    path: public/projects
    view:
      fields: [ date, slug, redirect, draft ]
    fields:
      - { name: slug, label: Slug, type: string }
      - { name: date, label: Date, type: date, required: true }
      - { name: draft, label: Draft, type: boolean }
      - { name: redirect, label: Redirect, type: string }
      - { name: body, label: Body, type: rich-text }
    filename: "{primary}.md"
    subfolders: false
  - name: text
    label: Text
    type: collection
    path: public/text
    view:
      fields: [ date, slug, redirect, draft ]
    fields:
      - { name: slug, label: Slug, type: string }
      - { name: date, label: Date, type: date, required: true }
      - { name: draft, label: Draft, type: boolean }
      - { name: source-name, label: "Source Name", type: string }
      - { name: source, label: "Source", type: string },
      - { name: redirect, label: Redirect, type: string }
      - { name: body, label: Body, type: rich-text }
    filename: "{primary}.md"
    subfolders: false
  - name: history
    label: History
    type: file
    path: public/history/index.md
    fields:
      - { name: layout, type: string, default: history.md, hidden: true }
      - { name: body, label: Body, type: rich-text }